spring:
  datasource:
    url: jdbc:postgresql://localhost:5455/product
    username: postgres
    password: q

  liquibase:
    change-log: changelogs/changelog-master.yaml
    url: jdbc:postgresql://localhost:5455/product
    user: postgres
    password: q