spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  application:
    name: product

  profiles:
    active: development

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/liquibase-master.yaml

  jpa:
    hibernate:
      ddl-auto: none