spring:
  datasource:
    driver-class-name: org.postgresql.Driver

  application:
    name: security

  profiles:
    active: development

  liquibase:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8282